apiVersion: skaffold/v4beta5
kind: Config
metadata:
  name: byteblaze
build:
  artifacts:
    - image: dominikmatracki/byteblaze
      docker:
        dockerfile: Dockerfile
  tagPolicy:
    sha256: {}
manifests:
  rawYaml:
    - k8s/deployment.yaml
